apiVersion: v1
kind: Secret
metadata:
  name: ionos-secret
  namespace: cert-manager
type: Opaque
stringData:
  # IONOS API Credentials (aus 1Password)
  IONOS_PUBLIC_PREFIX: "PLACEHOLDER_PUBLIC_PREFIX"
  IONOS_SECRET: "PLACEHOLDER_SECRET_KEY"
