apiVersion: v1
kind: Secret
metadata:
    name: repo-eneg-k8s-infrastructure-v2
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:ESX/,iv:9gSh4LvXVrWsSxjAusL+a0X42a14xTO9iPbnNhBtY2A=,tag:XcwQivR4liGEJJdtzGFuDw==,type:str]
    url: ENC[AES256_GCM,data:yb76mXvj856VGU9ipdJtWnAk2/gfrR8hCQVwHo7Y3nOkEwNsKpSQlQ6EBwYw1SkWx5ugiamO3bs=,iv:RtEGjHxiSgOqoQ3oLoAoZup+zIu0Qn+LjusK7rTa7ts=,tag:6F+kMkVij9Bqk3LIn9frHg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:myom8ald9S7ZAPbWOHZswU90k6w1gmtk0iSGqUaRGA7OcP/vSYzQkJDiKP4wVkr85tOrEKLRaslMnGBKCgbPwZsUar7TH0lZ0OUj6UE99G2YOXVTOowLXVXEHjGCrcNqAUaUJNxb84rpHwDZ57JUMyWFDMVn31LK2WYDBA4vPgCvV6S6mqZ9KuiRJD4qRQsDp72oRtGs7KkHJ3yw/lmJ5+4GtMyGQS5kcNJ+hhyXQ9EGxGFWAiCkj4PdcXVzAwPwpMmQ5mfln3dlf180ppDSXDCTosWRLHQHb8yBi9GBrZRZ4GUb5uGtObZB2TLe/f9kHDMYhBrsh0XNarFUNkN1EKxIDqIL/6j/fORMPocLdqPfukzczguqqbrL17ErUJG+n7XFCm62g2w8BuU8rARTO9EeOk6ekuLBRtPm72q0HkIP4pmRngq5HXLwm+fR4nok0xDP37TOsFuPgS0klS18+eXMph/t+1YJH9WAdGc7jlD0V3jLUk0I56VPomiGdo8v70eLn9gPNnT3cCTFek90sGm9mKvP1k7UxM0e,iv:+W6CZl+AHBPyzzkxnGufMxfS8GW/0AoQWI4LJlYS8L8=,tag:L1YbC7BbW9AF5Ns36LhYYA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVR0RWQyVmhEZU5JejVh
            Z1RGdlM3V0RZRUg5RmtIYm5TcGtxb1hrSTEwCjJqTHNSQlFWbzNDcEFFdkVVZURR
            aTNRMGVrYjZ2V294UzR3U0hlczAwWEkKLS0tIGgzTEFqR3JNVnp1eGs1YXJXaE9u
            L2dPNGMxQWFyU3RmVVRiWHp1RnZDbjgKinsbzF+SZAOOAAUDlc9vMJnwsoNQIHIO
            xjoACLamFgDNQFrYz/0+EapRNi2XqeCoKmFN0GOYJS9OUhvYRm5g9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T08:18:37Z"
    mac: ENC[AES256_GCM,data:ZMxB0yETNCGcI20BBhTVs9jVIKEXfEEFd3z9kvUyIIeQANDSEUK/hMOailqZ3f5tzboTv7RV7wwOPPec1l5zOd4iCvg21njpBxdPykGs295W8tcCX2YR3F8QF3t+McLoucWuUU0nIMlACHf73pSuDYsoU63a1+lr2KXLoo2xfZk=,iv:Ugvxq3W+2HZo/VzqSVpOLyVbGOVwTtVr5ogG+4kweR4=,tag:oSV7g+NecxTQQ24xeGmWJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
