apiVersion: v1
kind: Secret
metadata:
  name: repo-eneg-k8s-infrastructure-v2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:dhenkeeneg/eneg-k8s-infrastructure-v2.git
  sshPrivateKey: |
    # WIRD MANUELL ERSTELLT - NICHT IN GIT!
    # kubectl create secret ...
